### ISSUE TITLE
Provide means for consuming less memory

### ISSUE THREAD

**Issue by timonus** [Flipboard/FLAnimatedImage#115]
This is critical if one is to use `FLAnimatedImage` in memory constrained environments such as application extensions.

Things to consider:
- Allow for customization of preload buffer (definite savings)
- Allow for disabling of frame predrawing (questionable savings, requires spending time with instruments).

Started at https://github.com/Flipboard/FLAnimatedImage/tree/extension-considerations.

**Comment by timonus** [comment]
Here are some memory usage samples.

Sample project:
![bare](https://cloud.githubusercontent.com/assets/522951/12251379/747a28ac-b883-11e5-8212-06fb47fe9e16.png)

Sample project with no frame preloading permitted:
![reduced buffer](https://cloud.githubusercontent.com/assets/522951/12251389/7fd6d72c-b883-11e5-9bee-cd10983fd954.png)
*All allocations drops from 48 to 32MB*

Sample project with no frame preloading permitted and predrawing disabled:
![reduce predrawing](https://cloud.githubusercontent.com/assets/522951/12251402/8cc6596c-b883-11e5-8183-1dd26efbcc4b.png)
*"All anonymous VM" drops from 1.2GB to 400MB, meaning of this is unclear. Total is unchanged.*

**Comment by mitchellporter** [comment]
@timonus I'm currently experiencing some memory issues with FLAnimatedImage and trying to figure out how to fix them. You mentioned customizing the preload buffer and also disabling frame predrawing. 

How can I customize the preload buffer, and how can I disable frame predrawing? Really appreciate the help. FLAnimatedImage looks great onscreen in my app right now and I love using it, it's just that I'm seeing really high numbers in the CPU and Memory reports in Xcode's debug navigator tab.

**Comment by mitchellporter** [comment]
@timonus have been experiencing endless Anonymous VM growth today and  can't seem to figure it out. I stopped using the cocoapod and downloaded the current source files and was able to pass false/NO in the designate init for predrawing but that doesn't seem to help.

It looks like you had success with `Allow for customization of preload buffer (definite savings)`

How can I do this? I tried going to your https://github.com/Flipboard/FLAnimatedImage/tree/extension-considerations link but it goes to a 404.

**Comment by timonus** [comment]
Sorry for the 404, the relevant change is here: https://github.com/Flipboard/FLAnimatedImage/pull/117.

In order to use less memory I'd recommend using [this initializer](https://github.com/Flipboard/FLAnimatedImage/blob/master/FLAnimatedImage/FLAnimatedImage.h#L55) as follows:

```
FLAnimatedImage *image = [[FLAnimatedImage alloc] initWithAnimatedImageData:data optimalFrameCacheSize:1 predrawingEnabled:NO];
```

**Comment by timonus** [comment]
Closed, was resolved in https://github.com/Flipboard/FLAnimatedImage/pull/117.

**Comment by kean** [comment]
> have been experiencing endless Anonymous VM growth today

What you are looking at is probably a **transient** memory allocations (the number of bytes created and destroyed in a given time range). The FLAnimatedImage has a buffer for image frames. This buffer stores only a limited number of frames at the same time: frame-0, current frame and some prebuffered frames that are soon going to be required for rendering. Thus, FLAnimatedImage destroys and creates frames during the animation. 

Hence the constant "grows" of transient memory. Which isn't actually a grows, it's just an instrument showing you how much memory is being allocated and deallocated in a given time range.

![screen shot 2016-02-11 at 17 21 04](https://cloud.githubusercontent.com/assets/1567433/12978732/d9c5e674-d0e3-11e5-97ea-6332d01b1358.png)

The number of **persistent** bytes allocated always stays the same though, which means that there are absolutely no leaks.

**Comment by mitchellporter** [comment]
@kean You are correct, my Instruments results are similar to yours. Still though, after consulting someone else on this, they mentioned that it's abnormal to have that many transient objects and that 'Rapid allocations of memory is one of the things the system will kill you for'

That being said, I'm not sure whether I can ship a stable app with this or not. As much as `Instruments` shows that things are fine, I worry about the endlessly growing memory usage shown in Xcode's debug navigator.

Amy I worrying too much about this? I'd love to continue to use `FLAnimatedImage` but I worry about shipping an app that crashes or uses way too much memory.

**Comment by kean** [comment]
I don't have a proof (maybe someone could provide one?), but I think that it's quite all right to continuously alloc/dealloc relatively small portions of memory. iOS could kill your app only if you would try to allocate a huge portion of memory in a single alloc call (talking 100Mb+). That's not what happens here.

You could potentially play with `optimalFrameCacheSize` so that `FLAnimatedImage` would be able to keep all the frames in memory at the same time. But I doubt that it's even possible for relatively large GIF files (especially when they have a lot of frames). And that's what `FLAnimatedImage` actually already does for you:

```objective-c
// Calculate the optimal frame cache size: try choosing a larger buffer window depending on the predicted image size.
// It's only dependent on the image size & number of frames and never changes.
CGFloat animatedImageDataSize = CGImageGetBytesPerRow(self.posterImage.CGImage) * self.size.height * (self.frameCount - skippedFrameCount) / MEGABYTE;
if (animatedImageDataSize <= FLAnimatedImageDataSizeCategoryAll) {
    _frameCacheSizeOptimal = self.frameCount;
}
```

It would set the `frameCacheSizeOptimal` to the `frameCount` if it thinks that the buffer would fit into memory. It looks like a perfectly fine implementation as it is.

**Comment by mitchellporter** [comment]
@kean I spoke with a developer yesterday thatripped out the caching system and replaced it with NSCache and he was able to reduce the transients count to less than 20% of what it is now. I think the current structure of the library is flawed, in that NSCache needs to be implemented instead of their custom caching.

**Comment by kean** [comment]
@mitchellporter probably the best solution would be a buffer (budget) shared between images. It would cover at least two cases well:

- it would make it possible to store all the frames in memory when displaying 1 or 2 really large images
- it would prevent FLAnimatedImage from taking too much memory when displaying a lot of small images at the same time (unrealistic though based on the current setup, which is really conservative in terms of memory usage)

It would also be more predictable, and probably easier to configure too, if you want to trade-off between CPU and memory.

I doubt that NSCache itself has anything to do with it, it's just a dictionary with some auto-removal policy (hopefully, LRU), it's undocumented and iunpredictable. Might be better to have full control over buffers.

**Comment by kean** [comment]
As an afterthought, there is no need in a bigger buffer unless it can keep all the frames at the same time, or else frames would be redrawn each time anyway. Unless there is a way to store some part of the frames persistently in memory, while recreating others, but that sounds like nonsense :)
