### ISSUE TITLE
high memory usage 

### ISSUE THREAD

**Issue by if4lcon** [Flipboard/FLAnimatedImage#118]
I'm using FLAnimatedImageView in CollectionView with custom uiimageview the problem occur when displaying multiple gifs the frames played slowly

**Comment by timonus** [comment]
This may help https://github.com/Flipboard/FLAnimatedImage/pull/117.

**Comment by phpfalcon** [comment]
No noticeable difference 
```
cell.aimageView.frame = CGRectMake(0.0, 0.0, 78.0, 78.0);
FLAnimatedImage *image =[[FLAnimatedImage alloc] initWithAnimatedGIFData:ImageData optimalFrameCacheSize:0 predrawingEnabled:YES];
cell.aimageView.animatedImage = image;
```

**Comment by phpfalcon** [comment]
Should I resize the GIF first before using it with FLAnimatedImage ? 

My gifs have 8 only frames . although it doesn't play smoothly

**Comment by caughtinflux** [comment]
@phpfalcon you want to *disable* predrawing, since that is what takes up quite a lot of RAM

**Comment by caughtinflux** [comment]
Also, if you're displaying the same GIF multiple times, make sure each FLAnimatedImageView has a different instance of FLAnimatedImage.

**Comment by phpfalcon** [comment]
@caughtinflux Same thing here more gifs more delay on frames playing .. I'm not sure why this happening maybe flanimatedimageview doesn't work with uicollectionview

**Comment by caughtinflux** [comment]
Well I'm using FLAnimatedImage in Giffage, and we don't see any lag at all. How large are the GIFs?

**Comment by phpfalcon** [comment]
small actually .. this is peace of code maybe give you something :+1: 

		- (NSData *)grabImageDataFromAsset:(PHAsset *)asset
		{
		    __block NSData *imageAssetInfo;
		    PHImageRequestOptions *options = [[PHImageRequestOptions alloc] init];
		    options.synchronous = YES;
		    [[PHImageManager defaultManager] requestImageDataForAsset:asset
		                                                      options:options
		                                                resultHandler:
		     ^(NSData *imageData, NSString *dataUTI, UIImageOrientation orientation, NSDictionary *info) {
		         if ([info[@"PHImageResultIsInCloudKey"] isEqual:@YES]) {
		             // in the cloud
		             NSLog(@"in the cloud (sync grabImageDataFromAsset)");
		         }
		         imageAssetInfo = [info mutableCopy];
		         if (imageData) {
		             imageAssetInfo = imageData;
		         }
		     }];
		    return imageAssetInfo;
		}


		//in cellForItemAtIndexPath

		NSData *u = [self grabImageDataFromAsset:asset];
		FLAnimatedImage *image =[[FLAnimatedImage alloc] initWithAnimatedGIFData:u optimalFrameCacheSize:0 predrawingEnabled:NO];
		cell.aimageView.animatedImage = image;

**Comment by caughtinflux** [comment]
I don't think creating FLAnimatedImage in cellForRowAtIndexPath: every time is a very good idea, but other than that, i don't see anything that would cause the lag you mention

**Comment by phpfalcon** [comment]
maybe I need to move that code to ( willDisplayCell ) ?

**Comment by mitchellporter** [comment]
@caughtinflux I'm experiencing memory issues as well using a UICollectionView. You recommended to 'disable predrawing'. How can I easily do that? I can't seem to find a property that controls predrawing in the latest release, unless I'm missing it.

**Comment by wsq724439564** [comment]
FLAnimatedImage *image =[[FLAnimatedImage alloc] initWithAnimatedGIFData:u optimalFrameCacheSize:0 predrawingEnabled:NO];

it does not work, the memory always arising!!!

**Comment by yiplee** [comment]
UICollectionView just hide the cell when the cell is not visible or deleted from UICollectionView.
This will keep ```FLAnimatedImageView``` running as nothing changed on it. 
Override your custom collectionViewCell's ```- setHidden:``` and hide ```FLAnimatedImageView``` also to avoid this problem.
