### ISSUE TITLE
How to find out if image is gif?

### ISSUE THREAD

**Issue by cannyboy** [Flipboard/FLAnimatedImage#123]
Normally, I would have the luxury of just checking if the URL ended in ".gif", but unfortunately my URLs just end in a random series of characters. So how could I test if the image is a gif before deciding whether to use a UIImageView or a FLAnimatedImageView? 
I'm guessing you have to get the headers of the file somehow, but I don't want to have to get the whole file before deciding to do something with it.

**Comment by timonus** [comment]
1. Create a `CGImageSource` like so: https://github.com/Flipboard/FLAnimatedImage/blob/master/FLAnimatedImage/FLAnimatedImage.m#L204-L205
2. Get the image properties like so: https://github.com/Flipboard/FLAnimatedImage/blob/master/FLAnimatedImage/FLAnimatedImage.m#L230
3. Get the frame count like so: https://github.com/Flipboard/FLAnimatedImage/blob/master/FLAnimatedImage/FLAnimatedImage.m#L234

**Comment by caughtinflux** [comment]
You could test the first 3 bytes of the image to see if they read 'g', 'i',
and 'f'

On 02-Feb-2016, at 4:27 AM, cannyboy <notifications@github.com> wrote:

Normally, I would have the luxury of just checking if the URL ended in
".gif", but unfortunately my URLs just end in a random series of
characters. So how could I test if the image is a gif before deciding
whether to use a UIImageView or a FLAnimatedImageView?
I'm guessing you have to get the headers of the file somehow, but I don't
want to have to get the whole file before deciding to do something with it.

—
Reply to this email directly or view it on GitHub
<https://github.com/Flipboard/FLAnimatedImage/issues/123>.

**Comment by cannyboy** [comment]
(Posting for future reference)

I didn't understand how to implement the above suggestions, so I went with another solution.

Since FLAnimatedImageView returns nil anyway if the image is not a gif, I just check this before deciding whether to display a GIF or still image.


````
        let priority = DISPATCH_QUEUE_PRIORITY_DEFAULT
        dispatch_async(dispatch_get_global_queue(priority, 0)) {
            let gifImage = FLAnimatedImage(animatedGIFData: NSData(contentsOfURL: imageUrl))
            dispatch_async(dispatch_get_main_queue()) {
                if (gifImage != nil) {
                    self.gifImageView.animatedImage = gifImage
                } else {
                    self.gifImageView.animatedImage = nil
                    self.imageView.pin_setImageFromURL(imageUrl, placeholderImage: UIImage(named: "no_picture"))
                }
            }
        }
````

This is in a custom UICollectionViewCell which has a FLAnimatedImageView IBOutlet. If anyone knows a better solution, please let me know.

**Comment by kean** [comment]
There is an extension for FLAnimatedImageView that can display both animated and still images. Can't you just call `pin_setImageFromURL` on `FLAnimatedImageView`?

```objective-c
FLAnimatedImageView *animatedImageView = [[FLAnimatedImageView alloc] init];
[animatedImageView pin_setImageFromURL:[NSURL URLWithString:@"http://pinterest.com/flyingKitten.gif"]];
```

```objective-c
@implementation FLAnimatedImageView (PINRemoteImage)

- (void)pin_updateUIWithImage:(UIImage *)image animatedImage:(FLAnimatedImage *)animatedImage
{
    if (animatedImage) {
        self.animatedImage = animatedImage;
        [self setNeedsLayout];
    } else if (image) {
        self.image = image;
        [self setNeedsLayout];
    }
}
```

**Comment by cannyboy** [comment]
@kean yes, you're right. i was making it too complicated. Here's what I do:

````
imageView.contentMode = .ScaleAspectFill
imageView.pin_setImageFromURL(imageUrl, placeholderImage: UIImage(named: "no_picture"))
````

The `contentMode`  is there because the mode set in the xib does not seem to be followed.

**Comment by caughtinflux** [comment]
For posterity, here's an example of checking the given image data:
```
NSData *data = <fetched image data>;
BOOL isGIF = NO;
if (data.length > 3) {
    uint8_t *bytes = (uint8_t *)data;
    isGIF = (bytes[0] == 'g' && bytes[1] == 'i' && bytes[2] == 'f');
}
```
