### ISSUE TITLE
Investigate porting FLAnimatedImage over to Swift

### ISSUE THREAD

**Issue by raphaelschaad** [Flipboard/FLAnimatedImage#14]
Swift is Apple's new programming language.

**Comment by timonus** [comment]
Was investigated a fair bit, but I think it's good to keep as-is in ObjC for now. Some interesting projects:

- https://github.com/Flipboard/FLAnimatedImage/pull/55 (a branch, still on Swift 1.2)
- https://github.com/khaledmtaha/XAnimatedImage (a fork)
