### ISSUE TITLE
How to use "loopCompletionBlock" in Swift 3.0

### ISSUE THREAD

**Issue by dharmendrajadav** [Flipboard/FLAnimatedImage#158]
Hello,

I have successfully integrated "FLAnimatedImage" Objective-C code to my application. I want to display a gif image as a splash screen. So the objective is image should animated for one time only and then the main view controller should open. 

The image is animated perfectly now but it is in loop. It is animating in infinite loop. I have tried to change loopCount property by 1 and the image stopped animation but I was unable to get any call back for the completion of this operation.

I have also tried to call 'loopCompletionBlock' but I am unable to call this as it gives me the following error always:
**'Cannot call value of non-function type ((UInt) _> Void)!'**

Please guide me that How can I use this call back upon completion of the animation for the first time.

**Comment by kean** [comment]
Hey, tried this?

```swift
imageView.loopCompletionBlock = { _ in
            print("loop completed")
 }
```

**Comment by dharmendrajadav** [comment]
Thanks for the replay Kean and it worked for me. Thank you once again..!!

**Comment by appasaheb4** [comment]
Thread 1: Fatal error: Unexpectedly found nil while unwrapping an Optional values
