### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by skyline75489** [Flipboard/FLAnimatedImage#163]

**Comment by kean** [comment]
The last commit in `master` was made 8 month ago which seems self-explanatory.

**Comment by skyline75489** [comment]
So the answer is "yes"?...

JK . If Flipboard doesn't use this any more, it could just hand it over to community maintainers.

**Comment by raphaelschaad** [comment]
Flipboard is still using it AFAIK. What are the most important things the community would do?

**Comment by guxiaojie** [comment]
crashes a lot recently .

**Comment by raphaelschaad** [comment]
What device/OS combination? Do you have crash logs? A particular GIF that creates a repro?

**Comment by hfossli** [comment]
Well a number of unmanaged pull requests isn't looking good. Some dates back to 2015 just hanging in the air.

**Comment by mxcl** [comment]
I'm using [YYWebImage] instead, it works well, but it isn’t as modular as I'd like, eg. it requires a strict dependency on a caching library.

[YYWebImage]: https://github.com/ibireme/YYWebImage
