### ISSUE TITLE
podspec version is obsolete

### ISSUE THREAD

**Issue by zkhCreator** [Flipboard/FLAnimatedImage#204]
The last tag is 1.0.14, but the version on cocoapods is still 1.0.12. Please update cocoapods. Thanks

**Comment by JosephNK** [comment]
The version is still 1.0.12. :( 

Please Update~!

**Comment by raphaelschaad** [comment]
The latest is @ [1.0.15](https://github.com/CocoaPods/Specs/blob/master/Specs/2/a/8/FLAnimatedImage/1.0.15/FLAnimatedImage.podspec.json).
