### ISSUE TITLE
How to pause and resume gif ？ thanks

### ISSUE THREAD

**Issue by destinyxxl** [Flipboard/FLAnimatedImage#205]

**Comment by avivInmanage** [comment]
// setup
 NSString *strImageUrlGif = urlPath;
        NSURL *ImageUrlGif = [NSURL URLWithString:strImageUrlGif];
        FLAnimatedImage *imageGif = [FLAnimatedImage animatedImageWithGIFData:[NSData dataWithContentsOfURL:ImageUrlGif]];

        [imgGif setAnimatedImage:imageGif];
        [imgGif stopAnimating];

//running gif once
 [imgGif startAnimating];
    [imgGif setLoopCompletionBlock:^(NSUInteger loopCountRemaining) {
        [imgGif stopAnimating];
        [imgGif setLoopCompletionBlock:nil];
}];

**Comment by herokyo886** [comment]
> // setup
> NSString *strImageUrlGif = urlPath;
> NSURL *ImageUrlGif = [NSURL URLWithString:strImageUrlGif];
> FLAnimatedImage *imageGif = [FLAnimatedImage animatedImageWithGIFData:[NSData dataWithContentsOfURL:ImageUrlGif]];
> 
> ```
>     [imgGif setAnimatedImage:imageGif];
>     [imgGif stopAnimating];
> ```
> 
> //running gif once
> [imgGif startAnimating];
> [imgGif setLoopCompletionBlock:^(NSUInteger loopCountRemaining) {
> [imgGif stopAnimating];
> [imgGif setLoopCompletionBlock:nil];
> }];

How to disable animating every time when push another view and back
