### ISSUE TITLE
iOS 11.3 FLAnimatedImage animatedImageWithGIFData issue

### ISSUE THREAD

**Issue by iamluckykim** [Flipboard/FLAnimatedImage#207]
Hi!

First of all thanks for this library!
After iOS 11.3 update I ran into performance problem. When I'm invoke [FLAnimatedImage animatedImageWithGIFData:data] method on iOS 11.3, it works much slower rather than on iOS 11.2. I'm using dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_LOW, 0).

Here's an example project:
https://github.com/iamluckykim/FLAnimatedImagesTest

NSLog from iOS 11.2:
https://github.com/iamluckykim/FLAnimatedImagesTest/blob/master/Screenshots/NSLog_11.2.png

NSLog from iOS 11.3:
https://github.com/iamluckykim/FLAnimatedImagesTest/blob/master/Screenshots/NSLog_11.3.png

Time Profiler iOS 11.2:
https://github.com/iamluckykim/FLAnimatedImagesTest/blob/master/Screenshots/TimeProfiler_11_2.png

Time Profiler iOS 11.3:
https://github.com/iamluckykim/FLAnimatedImagesTest/blob/master/Screenshots/TimeProfiler_11_3.png

As we can see, CGImageSourceGetCount and CGImageSourceCopyProperties works much slower on iOS 11.3. 

How can I fix this problem?

**Comment by ryango** [comment]
Seeing this as well. Any luck?

**Comment by iamluckykim** [comment]
> Seeing this as well. Any luck?

Unfortunately I don't solve this problem yet

**Comment by running2011** [comment]
https://github.com/Flipboard/FLAnimatedImage/tree/dynamic-memory-category,try use this branch
