### ISSUE TITLE
Latest 1.0.13 and 1.0.14 version tags need to have their .podspec files registered in https://github.com/CocoaPods/Specs.git

### ISSUE THREAD

**Issue by JFrizzo** [Flipboard/FLAnimatedImage#216]
Hey, I just noticed that using the Podfile syntax `~> 1.0.0` resulted in 1.0.12 being pulled in, instead of 1.0.14 which is the latest version. Using the syntax `1.0.14` or `1.0.13` fails as well. I looked into it and it seems like you just need to add the .podspec files for each version to: https://github.com/CocoaPods/Specs.git

Here's the path to your repository reference in the specs repo:
https://github.com/CocoaPods/Specs/tree/734488a1b560a9e7ba3441fd8e0a614336153578/Specs/2/a/8/FLAnimatedImage

You can also see that cocoapods.org can't see these versions because of this:
https://cocoapods.org/pods/FLAnimatedImage

Let me know if I can help, thanks.

**Comment by muehlemann** [comment]
Any update on this?

**Comment by joneswah** [comment]
Any update on this?

**Comment by vinsent** [comment]
Any update on this?

**Comment by AlexanderPan** [comment]
Any update on this ~ ?

**Comment by oneofai** [comment]
Any update on this issues?

**Comment by raphaelschaad** [comment]
<img width="1394" alt="CleanShot 2021-01-30 at 21 36 17@2x" src="https://user-images.githubusercontent.com/439447/106367492-423a2e80-6343-11eb-9eef-87ec0307063a.png">
