### ISSUE TITLE
crash in +[FLAnimatedImage predrawnImageFromImage:] on iOS 10

### ISSUE THREAD

**Issue by Mrshang110** [Flipboard/FLAnimatedImage#219]
libsystem_platform.dylib    0x1806ffe6c    __platform_memmove + 108
ImageIO    0x1834bb000    GIFReadPlugin::copyImageBlockSet(InfoRec*, CGImageProvider*, CGRect, CGSize, __CFDictionary const*) + 796
ImageIO    0x1834bb000    GIFReadPlugin::copyImageBlockSet(InfoRec*, CGImageProvider*, CGRect, CGSize, __CFDictionary const*) + 796
ImageIO    0x1834ba6ac    GIFReadPlugin::CopyImageBlockSetProc(void*, CGImageProvider*, CGRect, CGSize, __CFDictionary const*) + 124
ImageIO    0x18331c77c    IIOImageProviderInfo::copyImageBlockSetWithOptions(CGImageProvider*, CGRect, CGSize, __CFDictionary const*) + 496
ImageIO    0x18331a708    IIOImageProviderInfo::CopyImageBlockSetWithOptions(void*, CGImageProvider*, CGRect, CGSize, __CFDictionary const*) + 356
CoreGraphics    0x182c5c09c    _img_blocks_create + 260
CoreGraphics    0x182c63ae8    _img_data_lock + 1868
CoreGraphics    0x182c63344    _CGSImageDataLock + 176
CoreGraphics    0x182a7c130    _ripc_AcquireImage + 712
CoreGraphics    0x182c77dec    _ripc_DrawImage + 676
CoreGraphics    0x182c67e90    _CGContextDrawImageWithOptions + 636
NewMissFresh    0x100642d60    +[FLAnimatedImage predrawnImageFromImage:] (FLAnimatedImage.m:707)
NewMissFresh    0x1006422ec    -[FLAnimatedImage imageAtIndex:] (FLAnimatedImage.m:0)
NewMissFresh    0x100641e40    ___42-[FLAnimatedImage addFrameIndexesToCache:]_block_invoke_3 (FLAnimatedImage.m:0)
Foundation    0x1821117f8    ___NSIndexSetEnumerate + 824
NewMissFresh    0x100641d6c    ___42-[FLAnimatedImage addFrameIndexesToCache:]_block_invoke_2 (FLAnimatedImage.m:481)
NewMissFresh    0x100cb6154    ___eventNewDispatchAsync_block_invoke + 48
libdispatch.dylib    0x1804fd200    __dispatch_call_block_and_release + 24
libdispatch.dylib    0x1804fd1c0    __dispatch_client_callout + 16
libdispatch.dylib    0x18050b444    __dispatch_queue_serial_drain + 928
libdispatch.dylib    0x1805009a8    __dispatch_queue_invoke + 652
libdispatch.dylib    0x18050b940    __dispatch_queue_override_invoke + 360
libdispatch.dylib    0x18050d38c    __dispatch_root_queue_drain + 572
libdispatch.dylib    0x18050d0ec    __dispatch_worker_thread3 + 124
libsystem_pthread.dylib    0x1807062b8    __pthread_wqthread + 1288
libsystem_pthread.dylib    0x180705da4    _start_wqthread + 4

binaryImages:

NewMissFresh    415F427F-FBC7-3FF0-9901-B6F81236980F    arm64    1
libsystem_pthread.dylib    548D3D6A-3B57-38F2-820E-0382C8D77C0E    arm64    0
libsystem_kernel.dylib    3BB31DBC-9985-3FA4-B33F-4948C9E2AF64    arm64    0
libsystem_platform.dylib    14630F9A-4281-3C0A-8197-64B8ADA8383B    arm64    0
libdyld.dylib    39AAA2DB-E1A1-313C-9C83-8CC0268A2EA0    arm64    0
libdispatch.dylib    3840477F-1DCB-32C5-BE29-D805A0B43D93    arm64    0
CoreFoundation    D72E357F-5B33-37AA-9693-522564A6032E    arm64    0
Foundation    8C727AEA-9F34-365F-B2FE-552669585011    arm64    0
CoreGraphics    1B546C1B-D4EB-334E-B850-E116B430E550    arm64    0
GraphicsServices    6D8EC4C7-41AE-3332-AE48-54A3C69F9C68    arm64    0
ImageIO    E1644285-7870-346F-BE11-E98073358914    arm64    0
UIKit    7EF942F4-3C3E-3E4A-A6CE-C127B68ECBAB    arm64    0

**Comment by kanshaoting** [comment]
Seeing this as well. Any luck?

**Comment by gerald8** [comment]
http://www.openradar.me/30196911#ag9zfm9wZW5yYWRhci1ocmRyFAsSB0NvbW1lbnQYgICAqIqs6ggM

**Comment by dxd214** [comment]
How to fix or bypass

**Comment by lxfrainbow** [comment]
How to fix???

**Comment by berchan** [comment]
https://github.com/vilanovi/UIImage-Additions/issues/2  
maybe it can be fixed

**Comment by yaomars** [comment]
@Mrshang110 Do you have a solution？？

**Comment by FinalFanTasyPHD** [comment]
make isPredrawingEnabled false

**Comment by matrush** [comment]
Per the radar:
> This should be addressed in iOS 10.3 beta 3 (14E5249d)
