### ISSUE TITLE
Hardcoded Frame Rate Divisor

### ISSUE THREAD

**Issue by viewDidAppear** [Flipboard/FLAnimatedImage#253]
## Overview

As of iPhone 13, more devices now have a 120Hz refresh rate. In `FLAnimatedImageView`, the refresh rate is defined as a `const` of 60, instead of using the `maximumFramesPerSecond` property available on `UIScreen`.

## Suggested Fix

Use `maximumFramesPerSecond` property available on UIScreen, instead of a hardcoded constant subject to change. The value can be cast to an NSTimeInterval (Double).

## Affected Apps

- Slack (iOS 15, iPhone 13 Pro)
GIFs play at ultra-speed.

**More apps may be affected.

**Comment by raphaelschaad** [comment]
Oof, good catch and suggested fix @topLayoutGuide ! Mind opening a PR? Happy to merge and cut a new released version for this.

**Comment by topLayoutGuide** [comment]
Thanks @raphaelschaad. Opened the PR. Please let me know if anything else needs to be done from my end.

**Comment by syncToCloud** [comment]
Any updates here on the GIF double speed issue? I see the PR was opened in September and hasn't been completed
