### ISSUE TITLE
在iPhone13Promax播放帧率异常加快

### ISSUE THREAD

**Issue by bullerliu** [Flipboard/FLAnimatedImage#257]
在iPhone13 promax播放Git图异常，播放帧率和速度异常加快

**Comment by matrush** [comment]
Have you tested with #256? I believe it should fix the issue already.

**Comment by stevehe-campray** [comment]
在iPhone13 promax播放GiF图异常问题修复后，非GIF图片不能正常显示。

**Comment by stevehe-campray** [comment]
我这里已经改了需要的话可以联系我602258720

**Comment by matrush** [comment]
#256 should resolve this, please pull latest and try again. Feel free to reopen if it's still an issue.
