### ISSUE TITLE
why do i can't pod search FLAnimatedImage 1.0.17

### ISSUE THREAD

**Issue by kimbo-fty** [Flipboard/FLAnimatedImage#264]
i execute pod search FLAnimatedImage, but result only show 1.0.16.

**Comment by matrush** [comment]
@raphaelschaad Can you help push the latest Podspec to trunk? Or you can add me as the contributor, I can help

**Comment by matrush** [comment]
https://github.com/CocoaPods/Specs/commit/5e7523774b301455e44db0a58c6379a5cb9d92da

Pushed 1.0.17
