### ISSUE TITLE
Animation Reset?

### ISSUE THREAD

**Issue by ViccAlexander** [Flipboard/FLAnimatedImage#52]
Is there a way to reset an animation back to frame 0 programmatically? Or better yet a way to load the image in a non-animated state?

**Comment by chiahsien** [comment]
I wish there be a public method called `reset` or something alike, it'd be a great help.
I'm making a walk-through page with GIFs in different pages and I want the GIF image plays from the beginning when it is displayed.

**Comment by johngibb** [comment]
Can't you just do:

    animagedImageView.animatedImage =  animagedImageView.animatedImage;

to restart the animation?

**Comment by timonus** [comment]
I think you'd have to set to `nil` first before setting back to the initial image, because setting that same image on it twice is a no-op. But yes, that should do it.

**Comment by pdpraful** [comment]
```
FLAnimatedImage  *temporaryImage = myAnimatedImageView.animatedImage;
myAnimatedImageView.animatedImage = nil;
myAnimatedImageView.animatedImage = temporaryImage;
```

The above code did a trick for me.
