### ISSUE TITLE
crash when setAnimatedImage involved

### ISSUE THREAD

**Issue by Moncter** [Flipboard/FLAnimatedImage#56]
Crashed: com.apple.main-thread
EXC_BAD_ACCESS KERN_INVALID_ADDRESS at 0xbf00bdf0 
getMethodNoSuper_nolock(objc_class*, objc_selector*) + 23
CFRelease + 560
_CGImagePlusFinalize + 120
CFRelease + 466
CFRelease + 466
_CGImageSourceFinalize + 134

CFRelease + 466

FLAnimatedImage.m line 316
-[FLAnimatedImage dealloc]

objc_object::sidetable_release(bool) + 174

FLAnimatedImageView.m line 62
-[FLAnimatedImageView setAnimatedImage:]

**Comment by Moncter** [comment]
I find the issue too!

**Comment by Moncter** [comment]
0
Crashed: com.apple.main-thread
EXC_BAD_ACCESS KERN_INVALID_ADDRESS at 0xe18a0461
 raw
0	libobjc.A.dylib	
objc_msgSend + 5
release
7	CoreFoundation	
CFRelease + 494
8
ImageIO	
_CGImageSourceFinalize + 186
9
CoreFoundation	
CFRelease + 494
10
MomoChat	
FLAnimatedImage.m line 316
-[FLAnimatedImage dealloc]
11
libobjc.A.dylib	
objc_object::sidetable_release(bool) + 166
12
MomoChat	
FLAnimatedImageView.m line 62
-[FLAnimatedImageView setAnimatedImage:]
13
MomoChat	
ChatEmotionCell.m line 95
-[ChatEmotionCell setMessageView:]

**Comment by raphaelschaad** [comment]
Unless there's more information provided, I can't do anything about it and will close this issue for now. Please feel free to reopen with more detailed information.
