### ISSUE TITLE
Animaton Rewind

### ISSUE THREAD

**Issue by pjebs** [Flipboard/FLAnimatedImage#57]
Is there anyway to detect when the animation has ended AFTER it has gone to the end and THEN gone backwards back to the start?

**Comment by raphaelschaad** [comment]
I'm not sure I fully understand you're question, but it seems to that you want a callback when playback has reached the end (and a new loop potentially -- depending on `loopCount`) will start?

Is this what you're looking for? https://github.com/Flipboard/FLAnimatedImage/pull/60

It would help to understand your use case better.

**Comment by pjebs** [comment]
Say there are 3 frames: A, B and C.

There should be a property i.e. loopBackwards = YES where after playing A, B, C, B, A, B, C ...

**Comment by raphaelschaad** [comment]
Got it. You want something like this: https://github.com/Flipboard/FLAnimatedImage/issues/47

Closing this issue as a dupe and adding some more detail to the linked issue.
