### ISSUE TITLE
clear background

### ISSUE THREAD

**Issue by danielgomezrico** [Flipboard/FLAnimatedImage#59]
If my gif have a clear background how can I make FLAnimatedImage to load it?

I'm using this:

`convenience init(gifResource: String) {
		let imagePath = NSBundle.mainBundle().pathForResource(gifResource, ofType: "gif")
		self.init(animatedGIFData: NSData(contentsOfFile: imagePath!))		
}`

**Comment by raphaelschaad** [comment]
Clear background or not shouldn't matter. FLAnimatedImage works well with GIFs that use transparency. Check out the predrawing code handling the alpha channel in FLAnimatedImage.m for that.

It seems you're using Swift. I'm actually not too familiar with Swift yet, but maybe the Swift port of FLAnimatedImage can help you: https://github.com/Flipboard/FLAnimatedImage/pull/55

**Comment by danielgomezrico** [comment]
It looks that my gif just have a color in the background... sorry

**Comment by raphaelschaad** [comment]
Can you please post and example? I can't repro and will close this issue otherwise. Thanks!

**Comment by MrBendel** [comment]
@raphaelschaad I think @danielgomezrico was saying he didn't realize his gif had a color in the background so I don't believe there is an issue in FLAnimatedImage. If i'm mistaken apologies around!

**Comment by danielgomezrico** [comment]
Yeah! there's no mistake, I apologise again.
