### ISSUE TITLE
Bring demo app to iOS 6

### ISSUE THREAD

**Issue by raphaelschaad** [Flipboard/FLAnimatedImage#62]
FLAnimatedImage supports iOS 6+ but the demo player is at 7+ because of some adjustments that need to happen before lowering the deployment target.

See previous (closed) issue: https://github.com/Flipboard/FLAnimatedImage/issues/7

**Comment by timonus** [comment]
We've dropped support for iOS 6 and 7 because 8+ is required for Carthage support, so this is obsolete.
