### ISSUE TITLE
speed change

### ISSUE THREAD

**Issue by keeetaka** [Flipboard/FLAnimatedImage#65]
Is there a way to change Gif Speed?
For example, change value of UISlider , gif speed changes.

I tried to change animationDuration.FLAnimatedImageView, but did not work well.

**Comment by raphaelschaad** [comment]
FLAnimatedImage doesn't support a way to alter the playback of a GIF. It would be trivial to expose an interface to tweak `@property (nonatomic, strong, readonly) NSArray *delayTimes;` but currently the design intents to honor the speed encoded in the original GIF file.

What's your use case?

**Comment by keeetaka** [comment]
Thank you for reply.
I want to see a GIF with slow speed or fast speed.

As it stands, will it be achieved to change `@property(nonatomic,strong,reawrite) NSArray *delayTimes`  or  `@property(nonatomic,strong,reawrite) NSUInteger loopCount` ??

**Comment by raphaelschaad** [comment]
Yeah, you can tinker with these properties (make them `readwrite` and assign new values etc.). I'm going to close this issue, as I don't plan to add support for this at the moment.

If you have any more questions on how to exactly implement certain details on this, StackOverflow would be great place to ask for specific coding help.

If you end up implementing a general solution that you feel good about, please don't hesitate to open a pull request and I'm happy to have a look at it.
