### ISSUE TITLE
imageLazilyCachedAtIndex problem

### ISSUE THREAD

**Issue by ingouackaz** [Flipboard/FLAnimatedImage#67]
Hi @raphaelschaad !

I'm trying  to retrieve all the images of a gif, howerver this only works when the size of the gif is less than 1.5 mb. Is that normal ? 

If yes, do you another way to retrieve all the images of a gif ?

Thank you :)

**Comment by caughtinflux** [comment]
You could poll FLAnimatesImage the same way FLAnimatedImageView does to
retrieve all the frames of the GIF; and it should work for larger ones as
well.
On 03-Mar-2015, at 7:51 pm, Roger Ingouacka <notifications@github.com>
wrote:

Hi @raphaelschaad <https://github.com/raphaelschaad> !

I'm trying to retrieve all the images of a gif, howerver this only works
when the size of the gif is less than 1.5 mb. Is that normal ?

If yes, do you another way to retrieve all the images of a gif ?

Thank you :)

—
Reply to this email directly or view it on GitHub
<https://github.com/Flipboard/FLAnimatedImage/issues/67>.

**Comment by ingouackaz** [comment]
Thanks @caughtinflux 

Do you have a little example, that shows me how to do this ?

**Comment by ingouackaz** [comment]
@caughtinflux  ?

**Comment by caughtinflux** [comment]
Have a look at FLAnimatedImage's [display link callback](https://github.com/Flipboard/FLAnimatedImage/blob/master/FLAnimatedImageDemo/FLAnimatedImage/FLAnimatedImageView.m#L234). However, FLAnimatedImage isn't exactly built for this; you could simply use one of the GIF to Animated UIImage libraries and get an array of all the frames in a GIF.

**Comment by timonus** [comment]
`FLAnimatedImage` isn't designed to pull each of the frames of an animated GIF, it's designed to play animated GIFs while minimally impacting performance, which means it often dynamically loads frame in and out of memory. If you need to get the frames of an animated GIF I'd recommend using a `CGImageSource` and `CGImageSourceCreateImageAtIndex` as we do [here](https://github.com/Flipboard/FLAnimatedImage/blob/master/FLAnimatedImage/FLAnimatedImage.m#L231).
