### ISSUE TITLE
Help with Swift

### ISSUE THREAD

**Issue by geennari** [Flipboard/FLAnimatedImage#68]
Ok, first I have my Gif in storyboard and I have the IBOutlet like this in my view:
```
@IBOutlet weak var imageGIF: FLAnimatedImageView!
```
But i'm receiving an error of NSUnknownKeyException: this class is not key value coding-compilant for the key imageGIF.

And second, how can I play any GIF in Swift? I'm kinda stuck in this for like a week.

**Comment by ts57** [comment]
Hi @geennari - did you ever find a solution to this?  I'm getting a nil outlet, Xcode 6.3.  I'm about to resort to a different solution: http://stackoverflow.com/questions/24485308/how-to-show-gif-into-uiimageview-in-swift?rq=1

**Comment by geennari** [comment]
Yes, I did. And in fact, that was the solution i found. I imported the Obj-C code to my project and everything went just fine, no problems. This is simple and easy to use.

**Comment by ts57** [comment]
Thanks for the quick reply!  Just found my issue, and I was being dumb - accessed the IBOutlet before it was loaded.
