### ISSUE TITLE
app crashes while trying imageWithData method

### ISSUE THREAD

**Issue by maha-ghonam** [Flipboard/FLAnimatedImage#69]
Hi,
i'm trying to use [FLAnimatedImage imageWithData:data] method but the app crashes with the following:

-[_UIAnimatedImage prepareAnimatedImageWithData:mode:]: unrecognized selector sent to instance 0x7fc15aec5220
- Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[_UIAnimatedImage prepareAnimatedImageWithData:mode:]: unrecognized selector sent to instance 0x7fc15aec5220'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010193cf35 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x00000001011c7bb7 objc_exception_throw + 45
	2   CoreFoundation                      0x000000010194404d -[NSObject(NSObject) doesNotRecognizeSelector:] + 205
	3   CoreFoundation                      0x000000010189c27c ___forwarding___ + 988
	4   CoreFoundation                      0x000000010189be18 _CF_forwarding_prep_0 + 120
	5   Emoji                               0x000000010084a814 -[FLAnimatedImage initWithImageData:mode:scale:] + 105
	6   Emoji                               0x000000010084aa9e +[FLAnimatedImage imageWithData:scale:] + 83

any thoughts?

Thanks in advance,

**Comment by raphaelschaad** [comment]
Looking at `-prepareAnimatedImageWithData:mode:`, you must be using the experimental branch ["uiimage-subclass"](https://github.com/Flipboard/FLAnimatedImage/commits/uiimage-subclass) which is far from done and I can't recommend using it yet or track GitHub issues on it. But if you want to play around with it, you can always do that and any suggestions or fixes are welcome.

**Comment by maha-ghonam** [comment]
thanks for your quick reply.
when do u think this branch will be available for use?

**Comment by raphaelschaad** [comment]
When it's done ;)

It won't exist as a branch, it will be merged to master and become FLAnimatedImage 2.0.
