### ISSUE TITLE
prevent creation of _UIAnimatedImage 

### ISSUE THREAD

**Issue by rounak** [Flipboard/FLAnimatedImage#71]
I know that this is probably unrelated to FLAnimatedImage, but I thought you might be able to help me out. I'm downloading gifs from the network, and they have a large file size, so I just want them to be plain old UIImage that take up minimum RAM.

What's happening though is that I'm getting `_UIAnimatedImage` in the imageview which are presumably being animated by the system (I'm using an FLAnimatedImageView). This baloons up memory usage(>500MB), causing my app to crash.

Do you have any pointers as to how to disable either the creation of `_UIAnimatedImage` or stopping the animation? Any methods I can set a break point on to track this? Thanks. (FWIW, SDWebImage is responsible for creating UIImages out of network data.)

Happy to provide more info.

**Comment by caughtinflux** [comment]
This is definitely the wrong place to be asking, but your issue is that SDWebImage is automatically creating the animated UIImage from the remote data.

**Comment by rounak** [comment]
Yeah I just figured that out. Apologies for posting that here.

**Comment by rounak** [comment]
welp. looks like there's no official way to disable GIF creation. Didn't really want to fork.

**Comment by raphaelschaad** [comment]
The fine people over at SDWebImage are looking into replacing that bit with FLAnimatedImage: https://github.com/rs/SDWebImage/issues/945

Here the relevant thread on FLAnimatedImage discussing the strategy:
https://github.com/Flipboard/FLAnimatedImage/issues/11

I think it's mostly on me to bang the `uiimage-subclass` branch (highly experimental, pushed a few weeks ago) in shape, then we can start integration, which would solve your problem.

**Comment by kean** [comment]
[DFImageManager](https://github.com/kean/DFImageManager) already features `FLAnimatedImage` integration. It has its own `UIImage` subclass `@interface DFAnimatedImage : UIImage`. I'm looking forward to replace it with FLAnimatedImage implementation.
