### ISSUE TITLE
Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by mtgomes** [Flipboard/FLAnimatedImage#75]
Hi,
I'm getting the following error while building. 
```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_DDLog", referenced from:
      objc-class-ref in FLAnimatedImage.o
      objc-class-ref in FLAnimatedImageView.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I'm sure that the solution is easy but, for the life of me, can't figure out the solution.
Any help is welcome!
Thanks!

**Comment by raphaelschaad** [comment]
Since you closed the issue, did you figure out what the problem was?

**Comment by mtgomes** [comment]
Hi @raphaelschaad. Thanks for the reply.

Actually I was a little bit early in closing the ticket. I thought it was working but the issue is back. I think it's somewhere in the integration with CocoaLumberjack. I've just tested in another project where I'm not using CocoaLumberjack and it works fine. When I add CocoaLumberjack I get that error. 

Any known issue with this integration?

**Comment by rynbyjn** [comment]
I get a similar error while running this on circle CI, but works locally from same command line build. My guess would be that this is due to having CocoaLumberjack as a dependency in another pod based on @mtgomes comments.
```
Undefined symbols for architecture i386:
  "_OBJC_CLASS_$_DDLog", referenced from:
      objc-class-ref in FLAnimatedImage.o
      objc-class-ref in FLAnimatedImageView.o
ld: symbol(s) not found for architecture i386
```

**Comment by GHawk11** [comment]
Search your build settings for this:
GCC_NO_COMMON_BLOCKS = YES;
Try changing it to "NO".
I had a similar message and this fixed it.

**Comment by bensarz** [comment]
@rynbyjn I'm getting the same issue here. Have you found a solution.?
@mtgomes why would you use CocoaLumberjack in this library and not declare it as a dependency?

**Comment by mtgomes** [comment]
@rynbyjn hum... I think that's what I'm doing, but the issue is still there..

**Comment by bensarz** [comment]
This is caused by the use of `use_frameworks!` in a Podfile.
Which means using this library prevents anyone from using Swift in their project.

**Comment by lexrus** [comment]
Same issue while building for Swift project.

**Comment by kdubb** [comment]
PR #101 allows building as a framework.  Specify 'FLAnimatedImage/Framework' and the CocoaPods !use_frameworks option will work correctly.

**Comment by mtgomes** [comment]
@kdubb Bingo! That fixes the issue!! Cheers!

**Comment by jackkyim** [comment]
@mtgomes I get similar error! How did fix the issue!

**Comment by timonus** [comment]
FLAnimatedImage now has no strong dependencies on CocoaLumberjack, so this should be resolved.
