### ISSUE TITLE
Can I detect corrupt GIF file?

### ISSUE THREAD

**Issue by sarunw** [Flipboard/FLAnimatedImage#76]
Sometime a GIF image not play till the end. I don't sure what is the cause of this problem. Is there any way I can detect corrupted/incomplted GIF file?

**Comment by timonus** [comment]
Corrupted GIFs will log that they're corrupted, but the frames that aren't corrupted will still play. You could manually write GIF corruption detection using `CGImageSource` I believe, `FLAnimatedImage` already handles them.
