### ISSUE TITLE
Allow sample GIFs to be downloaded in demo project in iOS 9

### ISSUE THREAD

**Issue by timonus** [Flipboard/FLAnimatedImage#89]
Because http was deprecated in iOS 9, the demo project fails to download its two images.

**Comment by raphaelschaad** [comment]
:-O Do you have a link to what new way Apple suggests?

I don't run iOS 9 beta yet. Do you know of a quick patch?

**Comment by tijoinc** [comment]
Quickest way to fix this is to either use HTTPs for those images or add `NSAllowsArbitraryLoads=YES` to a `NSAppTransportSecurity` dictionary in the demo project's info plist. This is described in Example E [here](http://www.neglectedpotential.com/2015/06/working-with-apples-application-transport-security/).

**Comment by timonus** [comment]
Resolved in https://github.com/Flipboard/FLAnimatedImage/pull/96.
