### ISSUE TITLE
How to get GIF playing time？

### ISSUE THREAD

**Issue by SummerWu** [Flipboard/FLAnimatedImage#91]
How to get GIF playing time？Have you any idea？

**Comment by raphaelschaad** [comment]
You'd sum all delay times: https://github.com/Flipboard/FLAnimatedImage/blob/master/FLAnimatedImageDemo/FLAnimatedImage/FLAnimatedImage.h#L53

I'll close this issue and hope this pointer helps. If you have any more questions, feel free to ask.

**Comment by mitchellporter** [comment]
@raphaelschaad Tried following that link but it 404's. Mind explaining again how to get the gif duration / playing time?

**Comment by eliburke** [comment]
@mitchellporter Take a look at the link text.. it just points to an older version of the header file for the library. 

Looking at the header, my guess is you need to do something with
`@property (nonatomic, strong, readonly) NSDictionary *delayTimesForIndexes; // Of type `NSTimeInterval` boxed in NSNumbers`
