### ISSUE TITLE
Sample or Demo SWIFT code using FLAnimatedImage

### ISSUE THREAD

**Issue by philhob** [Flipboard/FLAnimatedImage#99]
Hello,
I'm trying to use FLAnimatedImage with a new SWIFT application.
I imported the FLAnimatedImage.* and FLAnimatedImageView.* files.mI created the Bridging-Header.h. I added import Foundation. I have no compilation/build error.

I try to load the Gif into my ImageView with this code:
    @IBOutlet weak var animatedImageView: FLAnimatedImageView!
    animatedImageView.animatedImage = FLAnimatedImage(animatedGIFData: NSData(contentsOfFile: "chicken.gif"))
But it fails at application startup with:
exception 'NSInvalidArgumentException', reason: '-[UIImageView setAnimatedImage:]: unrecognized selector sent to instance 0x78e3c820'

I'm doing something wrong but I don't know why. 
Would anybody know of a working Swift sample code or demo code using FLAnimatedImage?

Thanks for any help.

**Comment by TomCorwine** [comment]
In your nib/storyboard, are you initializing a UIImageView, or FLAnimatedImageView? I suspect it's the former. Whatever view "animatedImageView" points to should have its class set to "FLAnimatedImageView."

**Comment by timonus** [comment]
Looks like you're not actually using an `FLAnimatedImageView`, but a `UIImageView` as @TomCorwine mentioned. You need to be using an `FLAnimatedImageView`.

**Comment by gkye** [comment]
I'm currently facing the same issue. The `UIImageView` within storyboard is set to `FLAnimatedImageView` and class is set to `FLAnimatedImageView` but I receive the same error as stated above.

**Comment by TedCorleone** [comment]
<img width="439" alt="Screen Shot 2019-12-10 at 11 54 50 AM" src="https://user-images.githubusercontent.com/7848894/70493841-10b14300-1b44-11ea-80ba-7a88dab70e27.png">


Make sure that you set correct custom class as `FLAnimatedImageView` for UIImageView.
